gateways:
    mother_duck:
        connection:
            type: motherduck
            database: coh3
            token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoia3Vyb2Noa2EuZ21haWwuY29tIiwiZW1haWwiOiJrdXJvY2hrYUBnbWFpbC5jb20iLCJ1c2VySWQiOiJhZWFlOGExYS04YWJlLTRlZjctOTU0MC0wNWY4ZWQzOWUwZGMiLCJpYXQiOjE3MTMwMzQyMTQsImV4cCI6MTc0NDU5MTgxNH0.Fx2slmrwBwNdXVl90EEHk9fadk-yV4Gpb0TXRfBj_L0 	
        state_connection:
            type: duckdb
            database: db.db

default_gateway: mother_duck

model_defaults:
    dialect: duckdb
